# Step 1: Build React app
FROM node:20 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Step 2: Serve with nginx
FROM nginx:1.27

# Remove default nginx static files
RUN rm -rf /usr/share/nginx/html/*

# Copy built React app to nginx html folder
COPY --from=build /app/dist /usr/share/nginx/html

# Copy your custom nginx config inside container
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
