# Generated by Django 5.2 on 2025-05-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramaccount',
            old_name='is_active',
            new_name='free_for_posting',
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='account_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
