# Generated by Django 5.2 on 2025-04-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instagramaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramaccount',
            name='password',
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='_password',
            field=models.TextField(db_column='password', default='password'),
        ),
    ]
