# Generated by Django 5.2 on 2025-05-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_active_instagramaccount_free_for_posting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediapost',
            old_name='is_posted',
            new_name='has_posted',
        ),
        migrations.AddField(
            model_name='mediapost',
            name='has_tried',
            field=models.BooleanField(default=False),
        ),
    ]
