# Generated by Django 5.2 on 2025-04-12 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_instagramaccount_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='account',
        ),
        migrations.RemoveField(
            model_name='postlog',
            name='post',
        ),
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('photo_video', 'Photo & Video'), ('reel', 'Reel')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('time_gap', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instagramaccount')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('status', models.CharField(max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('media_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.mediapost')),
            ],
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostLog',
        ),
    ]
