# Generated by Django 5.2 on 2025-05-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_is_posted_mediapost_has_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
