# Generated by Django 5.2 on 2025-04-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_account_remove_postlog_post_mediapost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramaccount',
            name='_password',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='last_login',
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='access_token',
            field=models.TextField(default='', max_length=500),
        ),
    ]
