# Generated by Django 5.2 on 2025-05-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_applicationuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='password',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='profile_picture',
            field=models.CharField(default='', max_length=500),
        ),
    ]
