# Generated by Django 5.2 on 2025-04-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_instagramaccount__password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediapost',
            old_name='description',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='mediapost',
            name='time_gap',
        ),
        migrations.AddField(
            model_name='mediapost',
            name='hashtags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='post_type',
            field=models.CharField(max_length=20),
        ),
    ]
