# Generated by Django 5.2 on 2025-04-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_description_mediapost_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='media_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
